

CREATE VIEW ESTIMATED_SELLING_PRICE AS
SELECT S.SUBCATEGORY_ID, S.DESCRIPTION,S.CATEGORY_ID,((S.AVG_PRICE*(100-S.DEPRECIATION))/100) AS 'ESTIMATED_SELLING_PRICE'
FROM SUBCATEGORY S JOIN CATEGORY C
ON S.CATEGORY_ID = C.CATEGORY_ID
WHERE S.AVG_PRICE>0



CREATE VIEW AVG_BIDS_NOT_SELECTED AS 
SELECT B.LISTING_ID, AVG(B.BID_AMOUNT) AS 'AVG_BIDS_NOT_SELECTED'
FROM BID B
WHERE BID_STATUS = 'NOT SELECTED'
GROUP BY B.LISTING_ID



CREATE VIEW CORRESPONDING_BUYER_AND_SELLER AS
SELECT L.SELLER_ID,S.NAME AS SELLER_NAME, P.BUYER_ID,B.NAME AS BUYER_NAME
FROM LISTING L
JOIN PURCHASE P
ON L.LISTING_ID = P.LISTING_ID
JOIN BUYER B
ON B.BUYER_ID = P.BUYER_ID
JOIN SELLER S
ON S.SELLER_ID = L.SELLER_ID


CREATE VIEW SHIPPING_DETAILS AS
SELECT S.CARRIER,P.BUYER_ID,S.ZIPCODE AS BUYER_ZIPCODE,B.REGION AS BUYER_REGION,     
S.SHIPPING_DATE,SHIPPING_COST,S1.SELLER_ID,L.SELLING_ZIPCODE,S1.REGION AS   
SELLER_REGION
FROM SHIPPING S JOIN LISTING L
ON S.LISTING_ID = L.LISTING_ID
JOIN PURCHASE P 
ON L.LISTING_ID = P.LISTING_ID
JOIN SELLER S1 
ON L.SELLER_ID = S1.SELLER_ID
JOIN BUYER B ON P.BUYER_ID = B.BUYER_ID
WHERE CARRIER IS NOT NULL
